/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IRegulationStatsInterface extends utils.Interface {
  functions: {
    "addBonded(uint256,uint256)": FunctionFragment;
    "addEpochInfo(uint256,uint256,uint256,uint256,uint256,uint256,uint256)": FunctionFragment;
    "addRedeemed(uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addBonded",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addEpochInfo",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "addRedeemed",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addBonded", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addEpochInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addRedeemed",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IRegulationStats extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IRegulationStatsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addBonded(
      epochNumber: BigNumberish,
      added: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addEpochInfo(
      epochNumber: BigNumberish,
      twap: BigNumberish,
      expanded: BigNumberish,
      boardroomFunding: BigNumberish,
      daoFunding: BigNumberish,
      marketingFunding: BigNumberish,
      insuranceFunding: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addRedeemed(
      epochNumber: BigNumberish,
      added: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addBonded(
    epochNumber: BigNumberish,
    added: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addEpochInfo(
    epochNumber: BigNumberish,
    twap: BigNumberish,
    expanded: BigNumberish,
    boardroomFunding: BigNumberish,
    daoFunding: BigNumberish,
    marketingFunding: BigNumberish,
    insuranceFunding: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addRedeemed(
    epochNumber: BigNumberish,
    added: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addBonded(
      epochNumber: BigNumberish,
      added: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    addEpochInfo(
      epochNumber: BigNumberish,
      twap: BigNumberish,
      expanded: BigNumberish,
      boardroomFunding: BigNumberish,
      daoFunding: BigNumberish,
      marketingFunding: BigNumberish,
      insuranceFunding: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    addRedeemed(
      epochNumber: BigNumberish,
      added: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    addBonded(
      epochNumber: BigNumberish,
      added: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addEpochInfo(
      epochNumber: BigNumberish,
      twap: BigNumberish,
      expanded: BigNumberish,
      boardroomFunding: BigNumberish,
      daoFunding: BigNumberish,
      marketingFunding: BigNumberish,
      insuranceFunding: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addRedeemed(
      epochNumber: BigNumberish,
      added: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addBonded(
      epochNumber: BigNumberish,
      added: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addEpochInfo(
      epochNumber: BigNumberish,
      twap: BigNumberish,
      expanded: BigNumberish,
      boardroomFunding: BigNumberish,
      daoFunding: BigNumberish,
      marketingFunding: BigNumberish,
      insuranceFunding: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addRedeemed(
      epochNumber: BigNumberish,
      added: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
