/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ILiquidityFund,
  ILiquidityFundInterface,
} from "../ILiquidityFund";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "addLiquidity",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ILiquidityFund__factory {
  static readonly abi = _abi;
  static createInterface(): ILiquidityFundInterface {
    return new utils.Interface(_abi) as ILiquidityFundInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILiquidityFund {
    return new Contract(address, _abi, signerOrProvider) as ILiquidityFund;
  }
}
