/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IRegulationStats,
  IRegulationStatsInterface,
} from "../IRegulationStats";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "epochNumber",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "added",
        type: "uint256",
      },
    ],
    name: "addBonded",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "epochNumber",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "twap",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "expanded",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "boardroomFunding",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "daoFunding",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "marketingFunding",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "insuranceFunding",
        type: "uint256",
      },
    ],
    name: "addEpochInfo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "epochNumber",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "added",
        type: "uint256",
      },
    ],
    name: "addRedeemed",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IRegulationStats__factory {
  static readonly abi = _abi;
  static createInterface(): IRegulationStatsInterface {
    return new utils.Interface(_abi) as IRegulationStatsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRegulationStats {
    return new Contract(address, _abi, signerOrProvider) as IRegulationStats;
  }
}
